-- MySQL Script generated by MySQL Workbench
-- Tue Dec 31 13:11:00 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema Trabalho
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Trabalho
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Trabalho` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
SHOW WARNINGS;
USE `Trabalho` ;

-- -----------------------------------------------------
-- Table `AGENDAMENTO_REALIZACAO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AGENDAMENTO_REALIZACAO` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `AGENDAMENTO_REALIZACAO` (
  `Resultado` VARCHAR(100) NULL DEFAULT NULL,
  `Data_Hora_Agendamento` DATETIME NOT NULL,
  `Realizacao` TINYINT(4) NOT NULL,
  `idTeste` INT(11) NOT NULL,
  `idAtleta` INT(11) NOT NULL,
  `idTecnico` INT(11) NOT NULL,
  `idMedico` INT(11) NOT NULL,
  PRIMARY KEY (`idAtleta`, `Data_Hora_Agendamento`),
  INDEX `fk_AGENDAMENTO_REALIZACAO_ATLETA1_idx` (`idAtleta` ASC) VISIBLE,
  INDEX `fk_AGENDAMENTO_REALIZACAO_MEDICO_idx` (`idMedico` ASC) VISIBLE,
  INDEX `fk_AGENDAMENTO_REALIZACAO_TECNICO_idx` (`idTecnico` ASC) VISIBLE,
  INDEX `fk_AGENDAMENTO_REALIZACAO_TESTE_idx` (`idTeste` ASC) VISIBLE,
  CONSTRAINT `fk_AGENDAMENTO_REALIZACAO_ATLETA1`
    FOREIGN KEY (`idAtleta`)
    REFERENCES `atleta` (`idAtleta`),
  CONSTRAINT `fk_AGENDAMENTO_REALIZACAO_MEDICO`
    FOREIGN KEY (`idMedico`)
    REFERENCES `medico` (`idMedico`),
  CONSTRAINT `fk_AGENDAMENTO_REALIZACAO_TECNICO`
    FOREIGN KEY (`idTecnico`)
    REFERENCES `tecnico_saude` (`idTecnico_Saude`),
  CONSTRAINT `fk_AGENDAMENTO_REALIZACAO_TESTE`
    FOREIGN KEY (`idTeste`)
    REFERENCES `teste` (`idTeste`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ATLETA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ATLETA` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ATLETA` (
  `idAtleta` INT(11) NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Morada` VARCHAR(45) NOT NULL,
  `Codigo_Postal` VARCHAR(8) NOT NULL,
  `NIF` INT(11) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `idModalidade` INT(11) NOT NULL,
  PRIMARY KEY (`idAtleta`),
  INDEX `fk_modalidade_idx` (`idModalidade` ASC) VISIBLE,
  INDEX `fk_codigo_postal_atleta_idx` (`Codigo_Postal` ASC) VISIBLE,
  CONSTRAINT `fk_codigo_postal_atleta`
    FOREIGN KEY (`Codigo_Postal`)
    REFERENCES `codigo_postal` (`Codigo_Postal`),
  CONSTRAINT `fk_modalidade`
    FOREIGN KEY (`idModalidade`)
    REFERENCES `modalidade` (`idModalidade`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `CODIGO_POSTAL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CODIGO_POSTAL` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `CODIGO_POSTAL` (
  `Codigo_Postal` VARCHAR(8) NOT NULL,
  `Concelho` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Codigo_Postal`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `MEDICO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MEDICO` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `MEDICO` (
  `idMedico` INT(11) NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Especialidade` VARCHAR(45) NOT NULL,
  `Morada` VARCHAR(45) NOT NULL,
  `Codigo_Postal` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`idMedico`),
  INDEX `fk_codigo_postal_medico_idx` (`Codigo_Postal` ASC) VISIBLE,
  CONSTRAINT `fk_codigo_postal_medico`
    FOREIGN KEY (`Codigo_Postal`)
    REFERENCES `codigo_postal` (`Codigo_Postal`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `MODALIDADE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MODALIDADE` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `MODALIDADE` (
  `idModalidade` INT(11) NOT NULL AUTO_INCREMENT,
  `designacao` VARCHAR(45) NOT NULL,
  `categoria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idModalidade`))
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `TECNICO_SAUDE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TECNICO_SAUDE` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `TECNICO_SAUDE` (
  `idTecnico_Saude` INT(11) NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Morada` VARCHAR(45) NOT NULL,
  `Codigo_Postal` VARCHAR(8) NOT NULL,
  `Categoria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTecnico_Saude`),
  INDEX `fk_codigo_postal_tecnico_idx` (`Codigo_Postal` ASC) VISIBLE,
  CONSTRAINT `fk_codigo_postal_tecnico`
    FOREIGN KEY (`Codigo_Postal`)
    REFERENCES `codigo_postal` (`Codigo_Postal`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `TESTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TESTE` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `TESTE` (
  `idTeste` INT(11) NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Preco` DECIMAL(6,2) NOT NULL,
  `Comparticipacao_estatal` DECIMAL(3,2) NOT NULL,
  PRIMARY KEY (`idTeste`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
