-- MySQL Script generated by MySQL Workbench
-- Mon Dec 30 23:48:15 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema Trabalho
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Trabalho` ;

-- -----------------------------------------------------
-- Schema Trabalho
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Trabalho` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
SHOW WARNINGS;
USE `Trabalho` ;

-- -----------------------------------------------------
-- Table `Trabalho`.`AGENDAMENTO_REALIZACAO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Trabalho`.`AGENDAMENTO_REALIZACAO` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Trabalho`.`AGENDAMENTO_REALIZACAO` (
  `Resultado` VARCHAR(100) NULL DEFAULT NULL,
  `Data_Agendamento` DATE NOT NULL,
  `Data_hora_Realizacao` DATETIME NOT NULL,
  `idTeste` INT(11) NOT NULL,
  `idAtleta` INT(11) NOT NULL,
  `idTecnico` INT(11) NOT NULL,
  `idMedico` INT(11) NOT NULL,
  PRIMARY KEY (`Data_hora_Realizacao`, `idAtleta`),
  CONSTRAINT `fk_AGENDAMENTO_REALIZACAO_ATLETA1`
    FOREIGN KEY (`idAtleta`)
    REFERENCES `Trabalho`.`atleta` (`idAtleta`),
  CONSTRAINT `fk_AGENDAMENTO_REALIZACAO_MEDICO`
    FOREIGN KEY (`idMedico`)
    REFERENCES `Trabalho`.`medico` (`idMedico`),
  CONSTRAINT `fk_AGENDAMENTO_REALIZACAO_TECNICO`
    FOREIGN KEY (`idTecnico`)
    REFERENCES `Trabalho`.`tecnico_saude` (`idTecnico_Saude`),
  CONSTRAINT `fk_AGENDAMENTO_REALIZACAO_TESTE`
    FOREIGN KEY (`idTeste`)
    REFERENCES `Trabalho`.`teste` (`idTeste`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE INDEX `fk_AGENDAMENTO_REALIZACAO_ATLETA1_idx` ON `Trabalho`.`AGENDAMENTO_REALIZACAO` (`idAtleta` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_AGENDAMENTO_REALIZACAO_MEDICO_idx` ON `Trabalho`.`AGENDAMENTO_REALIZACAO` (`idMedico` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_AGENDAMENTO_REALIZACAO_TECNICO_idx` ON `Trabalho`.`AGENDAMENTO_REALIZACAO` (`idTecnico` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_AGENDAMENTO_REALIZACAO_TESTE_idx` ON `Trabalho`.`AGENDAMENTO_REALIZACAO` (`idTeste` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Trabalho`.`ATLETA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Trabalho`.`ATLETA` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Trabalho`.`ATLETA` (
  `idAtleta` INT(11) NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Morada` VARCHAR(45) NOT NULL,
  `Codigo_Postal` VARCHAR(8) NOT NULL,
  `NIF` INT(11) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `idModalidade` INT(11) NOT NULL,
  PRIMARY KEY (`idAtleta`),
  CONSTRAINT `fk_modalidade`
    FOREIGN KEY (`idModalidade`)
    REFERENCES `Trabalho`.`modalidade` (`idModalidade`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE UNIQUE INDEX `idAtleta_UNIQUE` ON `Trabalho`.`ATLETA` (`idAtleta` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_modalidade_idx` ON `Trabalho`.`ATLETA` (`idModalidade` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Trabalho`.`CODIGO_POSTAL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Trabalho`.`CODIGO_POSTAL` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Trabalho`.`CODIGO_POSTAL` (
  `Codigo_Postal` VARCHAR(8) NOT NULL,
  `Concelho` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Codigo_Postal`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Trabalho`.`MEDICO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Trabalho`.`MEDICO` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Trabalho`.`MEDICO` (
  `idMedico` INT(11) NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Especialidade` VARCHAR(45) NOT NULL,
  `Morada` VARCHAR(45) NOT NULL,
  `Codigo_Postal` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`idMedico`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Trabalho`.`MODALIDADE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Trabalho`.`MODALIDADE` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Trabalho`.`MODALIDADE` (
  `idModalidade` INT(11) NOT NULL AUTO_INCREMENT,
  `designacao` VARCHAR(45) NOT NULL,
  `categoria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idModalidade`))
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Trabalho`.`TECNICO_SAUDE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Trabalho`.`TECNICO_SAUDE` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Trabalho`.`TECNICO_SAUDE` (
  `idTecnico_Saude` INT(11) NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Morada` VARCHAR(45) NOT NULL,
  `Codigo_Postal` VARCHAR(8) NOT NULL,
  `Categoria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTecnico_Saude`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE INDEX `codigo_postal_TS_idx` ON `Trabalho`.`TECNICO_SAUDE` (`Codigo_Postal` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Trabalho`.`TESTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Trabalho`.`TESTE` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Trabalho`.`TESTE` (
  `idTeste` INT(11) NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Preco` DECIMAL(6,2) NOT NULL,
  `Comparticipacao_estatal` DECIMAL(3,2) NOT NULL,
  PRIMARY KEY (`idTeste`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
